import 'package:social/widgets/custom_post_card.dart';

class AppSeedData {
  static List<PostModel> posts = [
    PostModel(
      id: '1',
      user: UserModel(
        id: '1',
        username: 'BeratARPA',
        displayName: 'Berat ARPA',
        profilePicture: 'assets/images/app_logo.png',
        isVerified: true,
      ),
      content:
          'Flutter ile harika bir uygulama geliştirdik! 🚀 Ne düşünüyorsunuz?',
      media: [
        PostMedia(type: MediaType.image, url: "assets/images/app_logo.png"),
        PostMedia(type: MediaType.video, url: "assets/videos/video1.mp4"),
        PostMedia(type: MediaType.video, url: "assets/videos/video2.mp4"),
        PostMedia(
          type: MediaType.poll,
          pollData: {
            "question": "En sevdiğiniz framework hangisi?",
            "options": ["Flutter", "React Native", "Native"],
            "votes": [45, 23, 18],
          },
        ),
      ],
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      likeCount: 124,
      commentCount: 18,
      shareCount: 5,
      isLiked: false,
      isSaved: false,
    ),
    PostModel(
      id: "3",
      user: UserModel(
        id: "1",
        username: "BeratARPA",
        displayName: "Berat ARPA",
        profilePicture: "assets/images/app_logo.png",
      ),
      content: "Bu hafta en çok dinlediğiniz şarkı hangisi? 🎶",
      media: [
        PostMedia(
          type: MediaType.poll,
          pollData: {
            "question": "En sevilen tür?",
            "options": ["Pop", "Rock", "Jazz", "Rap"],
            "votes": [50, 30, 15, 22],
          },
        ),
      ],
      createdAt: DateTime.now().subtract(const Duration(hours: 8)),
      likeCount: 120,
      commentCount: 40,
      shareCount: 12,
    ),
    PostModel(
      id: "2",
      user: UserModel(
        id: "1",
        username: "BeratARPA",
        displayName: "Berat ARPA",
        profilePicture: "assets/images/app_logo.png",
        isVerified: true,
      ),
      content: "AI ile yazılım geliştirme artık çok daha hızlı! 🤖",
      media: [
        PostMedia(type: MediaType.image, url: "assets/images/app_logo.png"),
      ],
      createdAt: DateTime.now().subtract(const Duration(minutes: 5)),
      likeCount: 540,
      commentCount: 87,
      shareCount: 44,
      isLiked: false,
    ),
    PostModel(
      id: "6",
      user: UserModel(
        id: "1",
        username: "BeratARPA",
        displayName: "Berat ARPA",
        profilePicture: "assets/images/app_logo.png",
      ),
      content: "Spor yapmayı hayatınızın bir parçası haline getirin! 💪",
      media: [],
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
      likeCount: 87,
      commentCount: 10,
      shareCount: 3,
    ),
    PostModel(
      id: "4",
      user: UserModel(
        id: "1",
        username: "BeratARPA",
        displayName: "Berat ARPA",
        profilePicture: "assets/images/app_logo.png",
        isVerified: false,
      ),
      content: "Paris'ten selamlar! 🗼",
      media: [
        PostMedia(type: MediaType.image, url: "assets/images/app_logo.png"),
      ],
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      likeCount: 900,
      commentCount: 210,
      shareCount: 70,
      isLiked: true,
      isSaved: true,
    ),
    PostModel(
      id: "8",
      user: UserModel(
        id: "1",
        username: "BeratARPA",
        displayName: "Berat ARPA",
        profilePicture: "assets/images/app_logo.png",
      ),
      content: "Bu ayın kitabı: 'Clean Code' 📚",
      media: [],
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
      likeCount: 67,
      commentCount: 19,
      shareCount: 5,
    ),
    PostModel(
      id: "5",
      user: UserModel(
        id: "1",
        username: "BeratARPA",
        displayName: "Berat ARPA",
        profilePicture: "assets/images/app_logo.png",
      ),
      content: "Flutter geliştiricileri böyle... 😂",
      media: [
        PostMedia(type: MediaType.video, url: "assets/videos/video2.mp4"),
      ],
      createdAt: DateTime.now().subtract(const Duration(hours: 12)),
      likeCount: 1300,
      commentCount: 430,
      shareCount: 210,
      isLiked: true,
    ),
    PostModel(
      id: '10',
      user: UserModel(
        id: '1',
        username: 'BeratARPA',
        displayName: "Berat ARPA",
        profilePicture: 'assets/images/app_logo.png',
        isVerified: true,
      ),
      content: 'Bugün kendime küçük bir mola verdim ✨',
      media: [],
      createdAt: DateTime.now().subtract(const Duration(minutes: 10)),
      likeCount: 12,
      commentCount: 3,
      shareCount: 0,
      isLiked: false,
      isSaved: false,
    ),
    PostModel(
      id: "7",
      user: UserModel(
        id: "1",
        username: 'BeratARPA',
        displayName: "Berat ARPA",
        profilePicture: "assets/images/app_logo.png",
        isVerified: true,
      ),
      content: "En sevdiğim pizzanın tarifini sizinle paylaşıyorum 🍕",
      media: [
        PostMedia(type: MediaType.video, url: "assets/videos/video1.mp4"),
      ],
      createdAt: DateTime.now().subtract(const Duration(hours: 48)),
      likeCount: 400,
      commentCount: 120,
      shareCount: 60,
    ),
    PostModel(
      id: "9",
      user: UserModel(
        id: "1",
        username: 'BeratARPA',
        displayName: "Berat ARPA",
        profilePicture: "assets/images/app_logo.png",
      ),
      content: "Doğanın huzuru paha biçilemez 🍃",
      media: [
        PostMedia(type: MediaType.image, url: "assets/images/app_logo.png"),
      ],
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
      likeCount: 230,
      commentCount: 54,
      shareCount: 21,
    ),
    PostModel(
      id: '11',
      user: UserModel(
        id: '1',
        username: 'BeratARPA',
        displayName: "Berat ARPA",
        profilePicture: 'assets/images/app_logo.png',
        isVerified: true,
      ),
      content: 'Uygulama simgemiz!',
      media: [
        PostMedia(type: MediaType.image, url: "assets/images/image1.jpg"),
      ],
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      likeCount: 124,
      commentCount: 18,
      shareCount: 5,
      isLiked: true,
      isSaved: false,
    ),
    PostModel(
      id: '12',
      user: UserModel(
        id: '1',
        username: 'BeratARPA',
        displayName: "Berat ARPA",
        profilePicture: 'assets/images/app_logo.png',
        isVerified: true,
      ),
      content: 'Father of the Turks',
      media: [
        PostMedia(type: MediaType.video, url: "assets/videos/video1.mp4"),
      ],
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      likeCount: 99999999,
      commentCount: 99999999,
      shareCount: 9999999,
      isLiked: true,
      isSaved: true,
    ),
    PostModel(
      id: '13',
      user: UserModel(
        id: '1',
        username: 'BeratARPA',
        displayName: "Berat ARPA",
        profilePicture: 'assets/images/app_logo.png',
        isVerified: true,
      ),
      content: 'Oy vermeye son 24 saat!',
      media: [
        PostMedia(
          type: MediaType.poll,
          pollData: {
            "question": "Hangi framework daha iyi?",
            "options": ["Flutter", "React Native", "SwiftUI"],
            "votes": [30, 15, 10],
          },
        ),
      ],
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      likeCount: 124,
      commentCount: 18,
      shareCount: 5,
      isLiked: false,
      isSaved: true,
    ),
    PostModel(
      id: "14",
      user: UserModel(
        id: "1",
        username: 'BeratARPA',
        displayName: "Berat ARPA",
        profilePicture: "assets/images/app_logo.png",
        isVerified: true,
      ),
      content: "Bugün gün batımı inanılmazdı 🌅",
      media: [
        PostMedia(type: MediaType.image, url: "assets/images/image2.jpg"),
      ],
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      likeCount: 120,
      commentCount: 34,
      shareCount: 10,
    ),
    PostModel(
      id: "15",
      user: UserModel(
        id: "1",
        username: "BeratARPA",
        displayName: "Berat ARPA",
        profilePicture: "assets/images/app_logo.png",
      ),
      content: "Favori kahvenizi seçin ☕️",
      media: [
        PostMedia(
          type: MediaType.poll,
          pollData: {
            "question": "Hangi kahveyi tercih edersin?",
            "options": ["Latte", "Espresso", "Cappuccino"],
            "votes": [12, 7, 5],
          },
        ),
      ],
      createdAt: DateTime.now().subtract(const Duration(hours: 5)),
      likeCount: 45,
      commentCount: 12,
      shareCount: 3,
    ),
    PostModel(
      id: "16",
      user: UserModel(
        id: "1",
        username: 'BeratARPA',
        displayName: "Berat ARPA",
        profilePicture: "assets/images/app_logo.png",
        isVerified: true,
      ),
      content: "Flutter ile video oynatma testi 🎥",
      media: [
        PostMedia(type: MediaType.video, url: "assets/videos/video2.mp4"),
      ],
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      likeCount: 300,
      commentCount: 50,
      shareCount: 22,
    ),
    PostModel(
      id: "17",
      user: UserModel(
        id: "1",
        username: 'BeratARPA',
        displayName: "Berat ARPA",
        profilePicture: "assets/images/app_logo.png",
      ),
      content: "Yeni profil fotoğrafım nasıl olmuş? 😎",
      media: [
        PostMedia(type: MediaType.image, url: "assets/images/app_logo.png"),
      ],
      createdAt: DateTime.now().subtract(const Duration(minutes: 30)),
      likeCount: 89,
      commentCount: 17,
      shareCount: 4,
    ),
  ];
}
