name: social
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter_native_splash: ^2.4.6
  connectivity_plus: ^6.1.4
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.8.0
  provider: ^6.1.5
  permission_handler: ^12.0.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  rename_app: ^1.6.3
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "resources/images/app_logo.png"
  android: true
  ios: true

  web:
    generate: true
    image_path: "resources/images/app_logo.png"
    background_color: "#ffffff"
    theme_color: "#4A90E2"