// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjb6Ydv3tWryEdiSD965JVAfeScumcnuY',
    appId: '1:438783857654:web:a1f2c22bca90319c53add7',
    messagingSenderId: '438783857654',
    projectId: 'socialapp-ba2e1',
    authDomain: 'socialapp-ba2e1.firebaseapp.com',
    storageBucket: 'socialapp-ba2e1.firebasestorage.app',
    measurementId: 'G-KZSDL7DR8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIGaGC5yfC3NOrsYs6wTIDEbNlc5K7Qkk',
    appId: '1:438783857654:android:b72be9ba45705bbc53add7',
    messagingSenderId: '438783857654',
    projectId: 'socialapp-ba2e1',
    storageBucket: 'socialapp-ba2e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBy0AwHQ_FaDd_tr-s09lG6vxHAmRRgog',
    appId: '1:438783857654:ios:b24226e0b939f4a453add7',
    messagingSenderId: '438783857654',
    projectId: 'socialapp-ba2e1',
    storageBucket: 'socialapp-ba2e1.firebasestorage.app',
    iosBundleId: 'com.isc.social',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBy0AwHQ_FaDd_tr-s09lG6vxHAmRRgog',
    appId: '1:438783857654:ios:493b54cbe69fd12c53add7',
    messagingSenderId: '438783857654',
    projectId: 'socialapp-ba2e1',
    storageBucket: 'socialapp-ba2e1.firebasestorage.app',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjb6Ydv3tWryEdiSD965JVAfeScumcnuY',
    appId: '1:438783857654:web:ca07c5aabb8ccb5153add7',
    messagingSenderId: '438783857654',
    projectId: 'socialapp-ba2e1',
    authDomain: 'socialapp-ba2e1.firebaseapp.com',
    storageBucket: 'socialapp-ba2e1.firebasestorage.app',
    measurementId: 'G-QNWZW3Q4LG',
  );
}
